version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    cooldown:
      default-days: 5
    open-pull-requests-limit: 0
