# Create a topic named "FilterNetexFileQueue" under project "test"
PUT http://localhost:8085/v1/projects/test/topics/FilterNetexFileQueue

###
# Create a subcription named "FilterNetexFileQueue"
PUT http://localhost:8085/v1/projects/test/subscriptions/FilterNetexFileQueue
Content-Type: application/json

{ "topic": "projects/test/topics/FilterNetexFileQueue" }

###
# Publish to the "FilterNetexFileQueue", to start filtering netex
# TXlUZXN0U3RyaW5n = MyTestString
POST http://localhost:8085/v1/projects/test/topics/FilterNetexFileQueue:publish
Content-Type: application/json

{
  "messages": [
    {
      "attributes": {
        "NetexFile": "rb_hur-aggregated-netex.zip",
        "Codespace": "hur",
        "CorrelationId": "testCorrelationId1"
      },
      "data": "TXlUZXN0U3RyaW5n"
    }
  ]
}

###
# Publish to the "FilterNetexFileQueue", to start filtering netex
# TXlUZXN0U3RyaW5n = MyTestString
POST http://localhost:8085/v1/projects/test/topics/FilterNetexFileQueue:publish
Content-Type: application/json

{
  "messages": [
    {
      "attributes": {
        "NetexFile": "rb_hur-aggregated-netex.zip",
        "Codespace": "hur",
        "CorrelationId": "testCorrelationId2"
      },
      "data": "TXlUZXN0U3RyaW5n"
    }
  ]
}