apiVersion: v1
kind: ConfigMap
metadata:
  name: ashur-application
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "common.labels" . | indent 4 }}
data:
  application.properties: |+
    ashur.gcp.marduk-project-id={{ .Values.configmap.gcp.mardukProjectId }}
    ashur.gcp.ashur-project-id={{ .Values.configmap.gcp.ashurProjectId }}
    ashur.gcp.ashur-bucket-name={{ .Values.configmap.gcp.ashurBucketName }}
    ashur.gcp.marduk-bucket-name={{ .Values.configmap.gcp.mardukBucketName }}
    
    ashur.netex.input-path={{ .Values.configmap.ashur.netex.inputPath }}
    ashur.netex.output-path={{ .Values.configmap.ashur.netex.outputPath }}
    ashur.netex.cleanup-enabled={{ .Values.configmap.ashur.netex.cleanupEnabled }}
    
    camel.component.google-pubsub.projectId={{ .Values.configmap.camel.component.googlePubsub.projectId }}
    
    spring.profiles.active=gcp
    
    management.endpoints.web.exposure.include=info, health, prometheus, env, metrics, loggers
    management.endpoints.prometheus.enabled=true
    management.metrics.endpoint.export.prometheus.enabled=true
